In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors

In [2]:
movies_recs = pd.read_csv('https://github.com/ArinB/CA05-kNN/raw/master/movies_recommendation_data.csv')
movies_recs.head()
#reads csv data and gives the first few rows

Movie ID          Movie Name  IMDB Rating  ...  Mystery  History  Label
0        58  The Imitation Game          8.0  ...        0        0      0
1         8          Ex Machina          7.7  ...        1        0      0
2        46    A Beautiful Mind          8.2  ...        0        0      0
3        62   Good Will Hunting          8.3  ...        0        0      0
4        97        Forrest Gump          8.8  ...        0        0      0

[5 rows x 11 columns]

In [3]:
movies_recs.drop(['Movie ID', 'Label'], axis = 1, inplace = True)
movies_recs.head()
#removes Movie ID and Label which are not useful in this recommender

Movie Name  IMDB Rating  Biography  ...  Crime  Mystery  History
0  The Imitation Game          8.0          1  ...      0        0        0
1          Ex Machina          7.7          0  ...      0        1        0
2    A Beautiful Mind          8.2          1  ...      0        0        0
3   Good Will Hunting          8.3          0  ...      0        0        0
4        Forrest Gump          8.8          0  ...      0        0        0

[5 rows x 9 columns]

In [4]:
movies_recs = movies_recs.append({'Movie Name' : 'The Post', 'IMDB Rating' : 7.2, 'Biography' : 1, 'Drama' : 1, 'Thriller' : 0, 'Comedy' : 0, 'Crime' : 0, 'Mystery' : 0, 'History' : 1}, ignore_index = True)
movies_recs.tail()
#inputs the movie 'The Post' which is indicated near the end of the assignment
#'The Post' will be used as the base movie to find similar ones to recommend

Movie Name  IMDB Rating  ...  Mystery  History
26  Spirit: Stallion of the Cimarron          7.1  ...        0        0
27                     Hacksaw Ridge          8.2  ...        0        1
28                  12 Years a Slave          8.1  ...        0        1
29                    Queen of Katwe          7.4  ...        0        0
30                          The Post          7.2  ...        0        1

[5 rows x 9 columns]

In [0]:
movie_numdata = movies_recs.copy()
movie_numdata.drop(['Movie Name'], axis = 1, inplace = True)
#get a numeric only data to fit in kNN algorithm

In [0]:
nbrs = NearestNeighbors(n_neighbors=6, algorithm='brute').fit(movie_numdata)
#sets the n_neighbors as 6 because the first would always return its own number
#uses 'brute' algorithm because of small sample and fits the numeric only data

In [7]:
distances, indices = nbrs.kneighbors(movie_numdata)
indices.astype(int)
print(indices)
#sets indices as integer in case of any problems and prints it
#as mentioned above, the first number returned is always its own id

[[ 0 16  2 29 28 27]
 [ 1  6 18 21 10  9]
 [ 2 16 29 27  3 28]
 [ 3 12  4  6 18 21]
 [ 4 12  3 15 17  2]
 [ 5 30  9 10 18 21]
 [ 6 21 18  9 10  3]
 [ 7 20 10  9 18 21]
 [ 8 22 24 14 19 17]
 [ 9 10 18 21  6 19]
 [ 9 10 18 21  6 19]
 [11 18 21  6 10  9]
 [12  4  3  6 17 15]
 [13 23 25  2 24 22]
 [14 19 26  8 22 24]
 [15 17 24 22  8  4]
 [16 29  2  0  6 28]
 [17 15 24 22  8 12]
 [21 18  9 10  6 19]
 [19 14 26  8 22 24]
 [20 26 19  7 14  1]
 [21 18  9 10  6 19]
 [22  8 24 17 14 19]
 [23 25 13 19 26 14]
 [24 22  8 17 15 14]
 [25  8 22 24 14 19]
 [26 19 14  8 22 24]
 [27 28  2 30 16 29]
 [28 27 30  2 16 29]
 [29 16  2 18 21  6]
 [30 28 27 29 16  2]]


In [0]:
def print_similar_movies(query=None, id=None):
  if query:
    sim_movs = movies_recs.loc[movies_recs['Movie Name'] == query].index[0]
    for id in indices[sim_movs][1:]:
      print(movies_recs.iloc[id]['Movie Name'])
#defines a function to return similar movies computed by brute kNN algorithm.
#starts with an if function to get the query which searches through the column
  #in movies_recs dataframe to return the movie name. The rows of id in indices
  #represent similar movies and when the numbers match the index numbers in
  #movies_recs dataframe then the movie names would be returned.

In [9]:
print_similar_movies(query='Forrest Gump')
#tests the function with movie 'Forrest Gump'

Interstellar
Good Will Hunting
Inception
Spirited Away
A Beautiful Mind


In [10]:
print_similar_movies(query='The Post')
#prints similar movies to 'The Post'

12 Years a Slave
Hacksaw Ridge
Queen of Katwe
The Wind Rises
A Beautiful Mind
